export interface VocabWord {
  id: string;
  german: string;
  english: string;
  example_de: string;
  example_en: string;
}

export const wordBank: VocabWord[] = [
  { id: "1", german: "die Absicht", english: "the intention", example_de: "Ich hatte keine böse Absicht.", example_en: "I had no bad intention." },
  { id: "2", german: "abwägen", english: "to weigh up / consider", example_de: "Ich muss die Vor- und Nachteile abwägen.", example_en: "I need to weigh up the pros and cons." },
  { id: "3", german: "die Anerkennung", english: "the recognition / acknowledgement", example_de: "Sie verdient mehr Anerkennung für ihre Arbeit.", example_en: "She deserves more recognition for her work." },
  { id: "4", german: "angemessen", english: "appropriate / adequate", example_de: "Deine Reaktion war völlig angemessen.", example_en: "Your reaction was completely appropriate." },
  { id: "5", german: "die Anpassung", english: "the adaptation / adjustment", example_de: "Die Anpassung an die neue Kultur dauert Zeit.", example_en: "The adaptation to the new culture takes time." },
  { id: "6", german: "ansprechen", english: "to address / to appeal to", example_de: "Er hat das Problem direkt angesprochen.", example_en: "He addressed the problem directly." },
  { id: "7", german: "der Anspruch", english: "the claim / entitlement / standard", example_de: "Sie stellt hohe Ansprüche an sich selbst.", example_en: "She sets high standards for herself." },
  { id: "8", german: "anstrengend", english: "exhausting / demanding", example_de: "Der Arbeitstag war sehr anstrengend.", example_en: "The working day was very exhausting." },
  { id: "9", german: "die Auseinandersetzung", english: "the confrontation / debate", example_de: "Eine sachliche Auseinandersetzung ist wichtig.", example_en: "A factual debate is important." },
  { id: "10", german: "ausführlich", english: "detailed / thorough", example_de: "Er hat das Thema ausführlich erklärt.", example_en: "He explained the topic in detail." },
  { id: "11", german: "die Auswirkung", english: "the impact / effect", example_de: "Die Auswirkungen des Klimawandels sind spürbar.", example_en: "The effects of climate change are noticeable." },
  { id: "12", german: "beeinflussen", english: "to influence", example_de: "Medien beeinflussen unsere Meinung stark.", example_en: "Media strongly influences our opinion." },
  { id: "13", german: "behaupten", english: "to claim / to assert", example_de: "Er behauptet, die Wahrheit zu kennen.", example_en: "He claims to know the truth." },
  { id: "14", german: "beitragen", english: "to contribute", example_de: "Jeder kann zur Lösung beitragen.", example_en: "Everyone can contribute to the solution." },
  { id: "15", german: "belegen", english: "to prove / to demonstrate", example_de: "Kannst du das mit Fakten belegen?", example_en: "Can you prove that with facts?" },
  { id: "16", german: "berücksichtigen", english: "to take into account / consider", example_de: "Wir müssen alle Faktoren berücksichtigen.", example_en: "We must take all factors into account." },
  { id: "17", german: "die Berufserfahrung", english: "the professional experience", example_de: "Mehrjährige Berufserfahrung ist erforderlich.", example_en: "Several years of professional experience is required." },
  { id: "18", german: "beschleunigen", english: "to accelerate / to speed up", example_de: "Die Digitalisierung beschleunigt viele Prozesse.", example_en: "Digitalization accelerates many processes." },
  { id: "19", german: "bestätigen", english: "to confirm", example_de: "Kannst du den Termin bestätigen?", example_en: "Can you confirm the appointment?" },
  { id: "20", german: "betonen", english: "to emphasize / to stress", example_de: "Sie betonte die Wichtigkeit der Zusammenarbeit.", example_en: "She emphasized the importance of cooperation." },
  { id: "21", german: "die Betrachtung", english: "the consideration / observation", example_de: "Bei näherer Betrachtung ergibt es Sinn.", example_en: "On closer consideration it makes sense." },
  { id: "22", german: "bewältigen", english: "to cope with / to overcome", example_de: "Er konnte die Krise gut bewältigen.", example_en: "He managed to cope with the crisis well." },
  { id: "23", german: "die Bewerbung", english: "the application", example_de: "Meine Bewerbung wurde abgelehnt.", example_en: "My application was rejected." },
  { id: "24", german: "bezeichnen", english: "to describe / to label", example_de: "Man bezeichnet ihn als Experten.", example_en: "He is described as an expert." },
  { id: "25", german: "die Beziehung", english: "the relationship / connection", example_de: "Die Beziehung zwischen beiden ist kompliziert.", example_en: "The relationship between the two is complicated." },
  { id: "26", german: "die Bildung", english: "the education / formation", example_de: "Bildung ist der Schlüssel zur Chancengleichheit.", example_en: "Education is the key to equal opportunity." },
  { id: "27", german: "dauerhaft", english: "permanent / lasting", example_de: "Wir suchen eine dauerhafte Lösung.", example_en: "We are looking for a lasting solution." },
  { id: "28", german: "die Debatte", english: "the debate", example_de: "Die politische Debatte war sehr hitzig.", example_en: "The political debate was very heated." },
  { id: "29", german: "dementsprechend", english: "accordingly / correspondingly", example_de: "Die Ergebnisse sind gut, dementsprechend sind wir zufrieden.", example_en: "The results are good, accordingly we are satisfied." },
  { id: "30", german: "die Denkweise", english: "the way of thinking / mindset", example_de: "Eine offene Denkweise ist entscheidend.", example_en: "An open mindset is crucial." },
  { id: "31", german: "deutlich", english: "clear / distinct / significant", example_de: "Der Unterschied ist deutlich sichtbar.", example_en: "The difference is clearly visible." },
  { id: "32", german: "die Einschränkung", english: "the restriction / limitation", example_de: "Es gibt gewisse Einschränkungen.", example_en: "There are certain restrictions." },
  { id: "33", german: "einschätzen", english: "to assess / to estimate", example_de: "Es ist schwer, die Lage einzuschätzen.", example_en: "It is difficult to assess the situation." },
  { id: "34", german: "einstellen", english: "to hire / to adjust / to stop", example_de: "Das Unternehmen stellt neue Mitarbeiter ein.", example_en: "The company is hiring new employees." },
  { id: "35", german: "die Einstellung", english: "the attitude / setting / hiring", example_de: "Eine positive Einstellung hilft im Alltag.", example_en: "A positive attitude helps in everyday life." },
  { id: "36", german: "empfindlich", english: "sensitive / delicate", example_de: "Er ist sehr empfindlich gegenüber Kritik.", example_en: "He is very sensitive to criticism." },
  { id: "37", german: "die Entwicklung", english: "the development", example_de: "Die technologische Entwicklung schreitet voran.", example_en: "Technological development is advancing." },
  { id: "38", german: "erfordern", english: "to require / to demand", example_de: "Die Aufgabe erfordert viel Konzentration.", example_en: "The task requires a lot of concentration." },
  { id: "39", german: "erkennen", english: "to recognize / to realize", example_de: "Er hat das Problem rechtzeitig erkannt.", example_en: "He recognized the problem in time." },
  { id: "40", german: "erweitern", english: "to expand / to broaden", example_de: "Ich möchte meinen Wortschatz erweitern.", example_en: "I want to expand my vocabulary." },
  { id: "41", german: "die Erwartung", english: "the expectation", example_de: "Die Erwartungen waren zu hoch.", example_en: "The expectations were too high." },
  { id: "42", german: "erzielen", english: "to achieve / to attain", example_de: "Wir haben gute Ergebnisse erzielt.", example_en: "We have achieved good results." },
  { id: "43", german: "das Fazit", english: "the conclusion / summary", example_de: "Das Fazit des Berichts ist positiv.", example_en: "The conclusion of the report is positive." },
  { id: "44", german: "fördern", english: "to promote / to support / to fund", example_de: "Die Regierung fördert erneuerbare Energien.", example_en: "The government promotes renewable energies." },
  { id: "45", german: "die Förderung", english: "the promotion / funding / support", example_de: "Ich habe eine staatliche Förderung bekommen.", example_en: "I received government funding." },
  { id: "46", german: "formulieren", english: "to formulate / to phrase", example_de: "Er kann seine Gedanken klar formulieren.", example_en: "He can formulate his thoughts clearly." },
  { id: "47", german: "der Fortschritt", english: "the progress / advance", example_de: "Der wissenschaftliche Fortschritt ist beeindruckend.", example_en: "Scientific progress is impressive." },
  { id: "48", german: "die Gegebenheit", english: "the given circumstance / reality", example_de: "Wir müssen uns den Gegebenheiten anpassen.", example_en: "We must adapt to the given circumstances." },
  { id: "49", german: "geprägt", english: "shaped / characterized", example_de: "Seine Kindheit hat ihn stark geprägt.", example_en: "His childhood strongly shaped him." },
  { id: "50", german: "die Gesellschaft", english: "the society / company", example_de: "Die Gesellschaft verändert sich ständig.", example_en: "Society is constantly changing." },
  { id: "51", german: "gewährleisten", english: "to ensure / to guarantee", example_de: "Wir müssen die Qualität gewährleisten.", example_en: "We must ensure the quality." },
  { id: "52", german: "gleichzeitig", english: "simultaneously / at the same time", example_de: "Er kann nicht gleichzeitig reden und schreiben.", example_en: "He cannot talk and write at the same time." },
  { id: "53", german: "das Gleichgewicht", english: "the balance / equilibrium", example_de: "Ein gesundes Gleichgewicht ist wichtig.", example_en: "A healthy balance is important." },
  { id: "54", german: "grundlegend", english: "fundamental / basic", example_de: "Das ist eine grundlegende Frage.", example_en: "That is a fundamental question." },
  { id: "55", german: "die Grundlage", english: "the basis / foundation", example_de: "Vertrauen ist die Grundlage jeder Beziehung.", example_en: "Trust is the foundation of every relationship." },
  { id: "56", german: "das Handeln", english: "the action / acting", example_de: "Schnelles Handeln war notwendig.", example_en: "Quick action was necessary." },
  { id: "57", german: "herausstellen", english: "to turn out / to highlight", example_de: "Es stellte sich heraus, dass er recht hatte.", example_en: "It turned out that he was right." },
  { id: "58", german: "hervorrufen", english: "to cause / to provoke", example_de: "Das kann starke Reaktionen hervorrufen.", example_en: "That can provoke strong reactions." },
  { id: "59", german: "die Hinsicht", english: "the respect / regard", example_de: "In dieser Hinsicht haben wir Fortschritte gemacht.", example_en: "In this respect we have made progress." },
  { id: "60", german: "hinterfragen", english: "to question / to challenge", example_de: "Man sollte alles kritisch hinterfragen.", example_en: "One should critically question everything." },
  { id: "61", german: "die Initiative", english: "the initiative", example_de: "Sie ergreift immer die Initiative.", example_en: "She always takes the initiative." },
  { id: "62", german: "inwiefern", english: "to what extent / in what way", example_de: "Inwiefern ist das relevant?", example_en: "To what extent is that relevant?" },
  { id: "63", german: "die Kompetenz", english: "the competence / skill", example_de: "Soziale Kompetenz ist sehr gefragt.", example_en: "Social competence is very much in demand." },
  { id: "64", german: "komplex", english: "complex", example_de: "Das ist ein sehr komplexes Thema.", example_en: "That is a very complex topic." },
  { id: "65", german: "konsequent", english: "consistent / consequent", example_de: "Man muss konsequent handeln.", example_en: "One must act consistently." },
  { id: "66", german: "der Kontext", english: "the context", example_de: "Das muss man im Kontext sehen.", example_en: "One must see that in context." },
  { id: "67", german: "die Kritik", english: "the criticism / critique", example_de: "Konstruktive Kritik hilft bei der Verbesserung.", example_en: "Constructive criticism helps with improvement." },
  { id: "68", german: "kritisch", english: "critical", example_de: "Man sollte kritisch denken.", example_en: "One should think critically." },
  { id: "69", german: "die Lage", english: "the situation / position", example_de: "Die wirtschaftliche Lage ist angespannt.", example_en: "The economic situation is tense." },
  { id: "70", german: "die Leistung", english: "the performance / achievement", example_de: "Seine schulische Leistung hat sich verbessert.", example_en: "His academic performance has improved." },
  { id: "71", german: "letztendlich", english: "ultimately / in the end", example_de: "Letztendlich liegt die Entscheidung bei dir.", example_en: "Ultimately the decision is up to you." },
  { id: "72", german: "die Lösung", english: "the solution", example_de: "Wir müssen eine nachhaltige Lösung finden.", example_en: "We need to find a sustainable solution." },
  { id: "73", german: "die Maßnahme", english: "the measure / step", example_de: "Die Regierung ergreift neue Maßnahmen.", example_en: "The government is taking new measures." },
  { id: "74", german: "der Missstand", english: "the grievance / shortcoming", example_de: "Dieser Missstand muss behoben werden.", example_en: "This grievance must be addressed." },
  { id: "75", german: "nachhaltig", english: "sustainable", example_de: "Wir brauchen nachhaltiges Wirtschaften.", example_en: "We need sustainable economic practices." },
  { id: "76", german: "nachweisen", english: "to prove / to demonstrate", example_de: "Er konnte seine Unschuld nachweisen.", example_en: "He was able to prove his innocence." },
  { id: "77", german: "die Notwendigkeit", english: "the necessity", example_de: "Die Notwendigkeit von Reformen ist klar.", example_en: "The necessity of reforms is clear." },
  { id: "78", german: "die Oberflächlichkeit", english: "the superficiality", example_de: "Oberflächlichkeit führt zu Missverständnissen.", example_en: "Superficiality leads to misunderstandings." },
  { id: "79", german: "objektiv", english: "objective", example_de: "Versuche, objektiv zu urteilen.", example_en: "Try to judge objectively." },
  { id: "80", german: "offensichtlich", english: "obvious / evident", example_de: "Das ist offensichtlich falsch.", example_en: "That is obviously wrong." },
  { id: "81", german: "die Perspektive", english: "the perspective / viewpoint", example_de: "Man sollte verschiedene Perspektiven berücksichtigen.", example_en: "One should consider different perspectives." },
  { id: "82", german: "prägen", english: "to shape / to characterize", example_de: "Erfahrungen prägen unsere Persönlichkeit.", example_en: "Experiences shape our personality." },
  { id: "83", german: "die Problematik", english: "the problem / issue", example_de: "Die Problematik ist vielschichtig.", example_en: "The issue is multifaceted." },
  { id: "84", german: "profitieren", english: "to profit / to benefit", example_de: "Beide Seiten können davon profitieren.", example_en: "Both sides can benefit from it." },
  { id: "85", german: "der Prozess", english: "the process / trial", example_de: "Lernen ist ein langer Prozess.", example_en: "Learning is a long process." },
  { id: "86", german: "reflektieren", english: "to reflect", example_de: "Man sollte regelmäßig über sein Verhalten reflektieren.", example_en: "One should regularly reflect on one's behavior." },
  { id: "87", german: "die Regelung", english: "the regulation / arrangement", example_de: "Es gibt klare Regelungen dafür.", example_en: "There are clear regulations for that." },
  { id: "88", german: "die Relevanz", english: "the relevance", example_de: "Die Relevanz dieses Themas ist hoch.", example_en: "The relevance of this topic is high." },
  { id: "89", german: "die Rolle", english: "the role", example_de: "Welche Rolle spielt Vertrauen in Beziehungen?", example_en: "What role does trust play in relationships?" },
  { id: "90", german: "der Rückgang", english: "the decline / decrease", example_de: "Es gibt einen Rückgang der Geburtenrate.", example_en: "There is a decline in the birth rate." },
  { id: "91", german: "die Schlussfolgerung", english: "the conclusion / inference", example_de: "Was ist deine Schlussfolgerung?", example_en: "What is your conclusion?" },
  { id: "92", german: "schildern", english: "to describe / to depict", example_de: "Sie schilderte die Ereignisse genau.", example_en: "She described the events accurately." },
  { id: "93", german: "die Schwierigkeit", english: "the difficulty", example_de: "Er hat große Schwierigkeiten damit.", example_en: "He has great difficulties with it." },
  { id: "94", german: "die Sichtweise", english: "the point of view / perspective", example_de: "Ich verstehe deine Sichtweise.", example_en: "I understand your point of view." },
  { id: "95", german: "sinnvoll", english: "meaningful / sensible", example_de: "Das ist eine sinnvolle Entscheidung.", example_en: "That is a sensible decision." },
  { id: "96", german: "der Standpunkt", english: "the standpoint / position", example_de: "Ich vertrete einen anderen Standpunkt.", example_en: "I hold a different standpoint." },
  { id: "97", german: "stärken", english: "to strengthen", example_de: "Sport stärkt das Immunsystem.", example_en: "Sport strengthens the immune system." },
  { id: "98", german: "der Stellenwert", english: "the importance / status", example_de: "Bildung hat einen hohen Stellenwert.", example_en: "Education has a high importance." },
  { id: "99", german: "die Tendenz", english: "the tendency / trend", example_de: "Es gibt eine Tendenz zur Digitalisierung.", example_en: "There is a trend towards digitalization." },
  { id: "100", german: "überwinden", english: "to overcome", example_de: "Er hat seine Angst überwunden.", example_en: "He overcame his fear." },
  { id: "101", german: "die Überzeugung", english: "the conviction / belief", example_de: "Ich handle nach meiner eigenen Überzeugung.", example_en: "I act according to my own conviction." },
  { id: "102", german: "überzeugen", english: "to convince / to persuade", example_de: "Er konnte mich nicht überzeugen.", example_en: "He could not convince me." },
  { id: "103", german: "umgehen", english: "to deal with / to handle", example_de: "Wie gehst du mit Stress um?", example_en: "How do you deal with stress?" },
  { id: "104", german: "umsetzen", english: "to implement / to put into practice", example_de: "Den Plan umzusetzen ist schwierig.", example_en: "Putting the plan into practice is difficult." },
  { id: "105", german: "unbedingt", english: "absolutely / by all means", example_de: "Das muss ich unbedingt ausprobieren.", example_en: "I absolutely must try that." },
  { id: "106", german: "unternehmen", english: "to undertake / to do something", example_de: "Wir sollten etwas dagegen unternehmen.", example_en: "We should do something about it." },
  { id: "107", german: "die Ursache", english: "the cause / reason", example_de: "Was ist die Ursache des Problems?", example_en: "What is the cause of the problem?" },
  { id: "108", german: "das Urteil", english: "the judgement / verdict", example_de: "Das Urteil des Richters war fair.", example_en: "The judge's verdict was fair." },
  { id: "109", german: "urteilen", english: "to judge", example_de: "Man sollte nicht vorschnell urteilen.", example_en: "One should not judge too hastily." },
  { id: "110", german: "die Verbindung", english: "the connection / link", example_de: "Es gibt eine enge Verbindung zwischen beiden.", example_en: "There is a close connection between the two." },
  { id: "111", german: "verbessern", english: "to improve", example_de: "Ich versuche, mein Deutsch zu verbessern.", example_en: "I am trying to improve my German." },
  { id: "112", german: "verdeutlichen", english: "to clarify / to illustrate", example_de: "Ein Beispiel kann das verdeutlichen.", example_en: "An example can illustrate that." },
  { id: "113", german: "die Verfügung", english: "the disposal / availability", example_de: "Das steht dir zur Verfügung.", example_en: "That is at your disposal." },
  { id: "114", german: "vergleichen", english: "to compare", example_de: "Man sollte Äpfel nicht mit Birnen vergleichen.", example_en: "One should not compare apples with pears." },
  { id: "115", german: "der Vergleich", english: "the comparison", example_de: "Im Vergleich zu früher hat sich viel verändert.", example_en: "Compared to before, a lot has changed." },
  { id: "116", german: "vermeiden", english: "to avoid", example_de: "Wir sollten unnötige Kosten vermeiden.", example_en: "We should avoid unnecessary costs." },
  { id: "117", german: "vermuten", english: "to suspect / to assume", example_de: "Ich vermute, dass er recht hat.", example_en: "I suspect that he is right." },
  { id: "118", german: "die Vernunft", english: "the reason / rationality", example_de: "Lass die Vernunft entscheiden.", example_en: "Let reason decide." },
  { id: "119", german: "vernünftig", english: "reasonable / sensible", example_de: "Das ist eine vernünftige Entscheidung.", example_en: "That is a reasonable decision." },
  { id: "120", german: "verringern", english: "to reduce / to decrease", example_de: "Wir müssen die Emissionen verringern.", example_en: "We must reduce emissions." },
  { id: "121", german: "verschieben", english: "to postpone / to shift", example_de: "Der Termin wurde auf nächste Woche verschoben.", example_en: "The appointment was postponed to next week." },
  { id: "122", german: "verstärken", english: "to strengthen / to intensify", example_de: "Das verstärkt den Eindruck.", example_en: "That intensifies the impression." },
  { id: "123", german: "das Vertrauen", english: "the trust / confidence", example_de: "Vertrauen muss man sich verdienen.", example_en: "Trust must be earned." },
  { id: "124", german: "verwirklichen", english: "to realize / to achieve", example_de: "Er hat seinen Traum verwirklicht.", example_en: "He realized his dream." },
  { id: "125", german: "die Vielfalt", english: "the diversity / variety", example_de: "Kulturelle Vielfalt bereichert die Gesellschaft.", example_en: "Cultural diversity enriches society." },
  { id: "126", german: "die Voraussetzung", english: "the prerequisite / condition", example_de: "Was sind die Voraussetzungen für diese Stelle?", example_en: "What are the prerequisites for this position?" },
  { id: "127", german: "der Vorteil", english: "the advantage / benefit", example_de: "Welche Vorteile hat dieses Modell?", example_en: "What advantages does this model have?" },
  { id: "128", german: "der Nachteil", english: "the disadvantage", example_de: "Jede Entscheidung hat Vor- und Nachteile.", example_en: "Every decision has advantages and disadvantages." },
  { id: "129", german: "der Wandel", english: "the change / transformation", example_de: "Der gesellschaftliche Wandel ist unaufhaltsam.", example_en: "Social change is unstoppable." },
  { id: "130", german: "der Widerspruch", english: "the contradiction", example_de: "Das ist ein klarer Widerspruch.", example_en: "That is a clear contradiction." },
  { id: "131", german: "widerspiegeln", english: "to reflect / to mirror", example_de: "Das spiegelt die aktuelle Lage wider.", example_en: "That reflects the current situation." },
  { id: "132", german: "die Wirksamkeit", english: "the effectiveness", example_de: "Die Wirksamkeit der Maßnahme ist bewiesen.", example_en: "The effectiveness of the measure is proven." },
  { id: "133", german: "der Zusammenhang", english: "the connection / context", example_de: "In welchem Zusammenhang steht das?", example_en: "In what context does that stand?" },
  { id: "134", german: "zusammenfassen", english: "to summarize", example_de: "Kannst du das kurz zusammenfassen?", example_en: "Can you briefly summarize that?" },
  { id: "135", german: "der Zweck", english: "the purpose / aim", example_de: "Was ist der Zweck dieser Maßnahme?", example_en: "What is the purpose of this measure?" },
  { id: "136", german: "abbrechen", english: "to break off / to discontinue", example_de: "Er hat sein Studium abgebrochen.", example_en: "He discontinued his studies." },
  { id: "137", german: "abgeben", english: "to hand in / to submit", example_de: "Wann musst du die Arbeit abgeben?", example_en: "When do you have to hand in the work?" },
  { id: "138", german: "ablaufen", english: "to expire / to proceed", example_de: "Mein Visum ist abgelaufen.", example_en: "My visa has expired." },
  { id: "139", german: "der Abschnitt", english: "the section / paragraph", example_de: "Lies den zweiten Abschnitt genau.", example_en: "Read the second section carefully." },
  { id: "140", german: "die Abwechslung", english: "the variety / change", example_de: "Abwechslung im Alltag ist wichtig.", example_en: "Variety in everyday life is important." },
  { id: "141", german: "achten auf", english: "to pay attention to", example_de: "Du solltest mehr auf deine Gesundheit achten.", example_en: "You should pay more attention to your health." },
  { id: "142", german: "der Alltag", english: "everyday life", example_de: "Der Alltag kann manchmal sehr stressig sein.", example_en: "Everyday life can sometimes be very stressful." },
  { id: "143", german: "die Angelegenheit", english: "the matter / affair", example_de: "Das ist eine persönliche Angelegenheit.", example_en: "That is a personal matter." },
  { id: "144", german: "angehören", english: "to belong to / to be a member of", example_de: "Er gehört einer Minderheit an.", example_en: "He belongs to a minority." },
  { id: "145", german: "anknüpfen", english: "to connect / to follow on from", example_de: "Ich möchte an das Gesagte anknüpfen.", example_en: "I would like to follow on from what was said." },
  { id: "146", german: "annehmen", english: "to accept / to assume", example_de: "Ich nehme an, dass du recht hast.", example_en: "I assume that you are right." },
  { id: "147", german: "anregen", english: "to stimulate / to suggest", example_de: "Das regt zum Nachdenken an.", example_en: "That stimulates thought." },
  { id: "148", german: "die Ausnahme", english: "the exception", example_de: "Das ist eine Ausnahme, keine Regel.", example_en: "That is an exception, not a rule." },
  { id: "149", german: "ausreichend", english: "sufficient / adequate", example_de: "Die Informationen sind nicht ausreichend.", example_en: "The information is not sufficient." },
  { id: "150", german: "ausüben", english: "to practice / to exercise", example_de: "Er übt einen großen Einfluss aus.", example_en: "He exercises a great influence." },
  { id: "151", german: "der Bedarf", english: "the need / demand / requirement", example_de: "Es gibt einen hohen Bedarf an Fachkräften.", example_en: "There is a high demand for skilled workers." },
  { id: "152", german: "bedeutsam", english: "significant / meaningful", example_de: "Das war ein bedeutsamer Moment.", example_en: "That was a significant moment." },
  { id: "153", german: "die Bedingung", english: "the condition / requirement", example_de: "Das ist eine wichtige Bedingung.", example_en: "That is an important condition." },
  { id: "154", german: "beeindrucken", english: "to impress", example_de: "Sein Wissen hat mich sehr beeindruckt.", example_en: "His knowledge impressed me greatly." },
  { id: "155", german: "beeinträchtigen", english: "to impair / to affect negatively", example_de: "Der Lärm beeinträchtigt die Konzentration.", example_en: "The noise impairs concentration." },
  { id: "156", german: "befassen mit", english: "to deal with / to concern oneself with", example_de: "Ich befasse mich mit diesem Thema.", example_en: "I am dealing with this topic." },
  { id: "157", german: "begründen", english: "to justify / to give reasons for", example_de: "Kannst du deine Entscheidung begründen?", example_en: "Can you justify your decision?" },
  { id: "158", german: "die Begründung", english: "the justification / reasoning", example_de: "Deine Begründung überzeugt mich nicht.", example_en: "Your reasoning does not convince me." },
  { id: "159", german: "bemerkenswert", english: "remarkable / notable", example_de: "Das ist eine bemerkenswerte Leistung.", example_en: "That is a remarkable achievement." },
  { id: "160", german: "die Bereitschaft", english: "the willingness / readiness", example_de: "Die Bereitschaft zur Veränderung ist entscheidend.", example_en: "The willingness to change is crucial." },
  { id: "161", german: "beschränken", english: "to limit / to restrict", example_de: "Wir müssen den Konsum beschränken.", example_en: "We must limit consumption." },
  { id: "162", german: "besorgniserregend", english: "worrying / alarming", example_de: "Die Entwicklung ist besorgniserregend.", example_en: "The development is worrying." },
  { id: "163", german: "bestehen aus", english: "to consist of", example_de: "Das Team besteht aus zehn Personen.", example_en: "The team consists of ten people." },
  { id: "164", german: "beziehen auf", english: "to refer to / to relate to", example_de: "Worauf beziehst du dich?", example_en: "What are you referring to?" },
  { id: "165", german: "differenzieren", english: "to differentiate / to distinguish", example_de: "Man muss hier klar differenzieren.", example_en: "One must clearly differentiate here." },
  { id: "166", german: "die Diskrepanz", english: "the discrepancy", example_de: "Es gibt eine große Diskrepanz zwischen Wort und Tat.", example_en: "There is a big discrepancy between word and deed." },
  { id: "167", german: "eingreifen", english: "to intervene", example_de: "Die Polizei musste eingreifen.", example_en: "The police had to intervene." },
  { id: "168", german: "einleiten", english: "to initiate / to introduce", example_de: "Wir müssen Veränderungen einleiten.", example_en: "We must initiate changes." },
  { id: "169", german: "entsprechen", english: "to correspond to / to meet", example_de: "Das entspricht nicht meinen Erwartungen.", example_en: "That does not meet my expectations." },
  { id: "170", german: "erläutern", english: "to explain / to elaborate", example_de: "Könnten Sie das bitte erläutern?", example_en: "Could you please elaborate on that?" },
  { id: "171", german: "ermöglichen", english: "to enable / to make possible", example_de: "Das ermöglicht neue Chancen.", example_en: "That enables new opportunities." },
  { id: "172", german: "erörtern", english: "to discuss / to examine", example_de: "Wir erörtern das Thema ausführlich.", example_en: "We discuss the topic in detail." },
  { id: "173", german: "erschöpft", english: "exhausted", example_de: "Nach der langen Reise bin ich völlig erschöpft.", example_en: "After the long journey I am completely exhausted." },
  { id: "174", german: "das Ergebnis", english: "the result / outcome", example_de: "Das Ergebnis war überraschend.", example_en: "The result was surprising." },
  { id: "175", german: "festhalten", english: "to hold on to / to record / to state", example_de: "Lass uns die wichtigsten Punkte festhalten.", example_en: "Let us record the most important points." },
  { id: "176", german: "feststellen", english: "to determine / to notice", example_de: "Ich habe festgestellt, dass etwas nicht stimmt.", example_en: "I have noticed that something is wrong." },
  { id: "177", german: "die Forderung", english: "the demand / requirement", example_de: "Die Forderungen der Gewerkschaft sind klar.", example_en: "The union's demands are clear." },
  { id: "178", german: "die Gesamtheit", english: "the totality / entirety", example_de: "In seiner Gesamtheit ist das Projekt gut.", example_en: "In its entirety the project is good." },
  { id: "179", german: "die Gewissheit", english: "the certainty", example_de: "Es gibt keine absolute Gewissheit.", example_en: "There is no absolute certainty." },
  { id: "180", german: "globalisieren", english: "to globalize", example_de: "Die Welt wird immer mehr globalisiert.", example_en: "The world is becoming increasingly globalized." },
  { id: "181", german: "die Globalisierung", english: "globalization", example_de: "Die Globalisierung hat Vor- und Nachteile.", example_en: "Globalization has advantages and disadvantages." },
  { id: "182", german: "der Grund", english: "the reason / ground", example_de: "Aus welchem Grund hat er abgelehnt?", example_en: "For what reason did he decline?" },
  { id: "183", german: "herausfordern", english: "to challenge", example_de: "Diese Aufgabe fordert mich heraus.", example_en: "This task challenges me." },
  { id: "184", german: "hervorgehen", english: "to emerge / to result from", example_de: "Daraus geht hervor, dass wir handeln müssen.", example_en: "From this it emerges that we must act." },
  { id: "185", german: "das Hindernis", english: "the obstacle", example_de: "Bürokratie ist oft ein Hindernis.", example_en: "Bureaucracy is often an obstacle." },
  { id: "186", german: "die Hypothese", english: "the hypothesis", example_de: "Diese Hypothese muss noch bewiesen werden.", example_en: "This hypothesis still needs to be proven." },
  { id: "187", german: "identifizieren", english: "to identify", example_de: "Wir müssen das Problem identifizieren.", example_en: "We need to identify the problem." },
  { id: "188", german: "implizieren", english: "to imply", example_de: "Was impliziert diese Aussage?", example_en: "What does this statement imply?" },
  { id: "189", german: "integrieren", english: "to integrate", example_de: "Es ist wichtig, Migranten zu integrieren.", example_en: "It is important to integrate migrants." },
  { id: "190", german: "die Integration", english: "the integration", example_de: "Die Integration gelingt nur mit gegenseitigem Respekt.", example_en: "Integration only succeeds with mutual respect." },
  { id: "191", german: "intensiv", english: "intensive / intense", example_de: "Die Vorbereitung war sehr intensiv.", example_en: "The preparation was very intensive." },
  { id: "192", german: "interpretieren", english: "to interpret", example_de: "Wie interpretierst du diesen Satz?", example_en: "How do you interpret this sentence?" },
  { id: "193", german: "die Konsequenz", english: "the consequence", example_de: "Jede Entscheidung hat Konsequenzen.", example_en: "Every decision has consequences." },
  { id: "194", german: "der Konflikt", english: "the conflict", example_de: "Konflikte müssen offen angesprochen werden.", example_en: "Conflicts must be addressed openly." },
  { id: "195", german: "mangeln an", english: "to lack", example_de: "Es mangelt an konkreten Lösungen.", example_en: "There is a lack of concrete solutions." },
  { id: "196", german: "der Mangel", english: "the lack / shortage", example_de: "Ein Mangel an Schlaf schadet der Gesundheit.", example_en: "A lack of sleep is harmful to health." },
  { id: "197", german: "die Methode", english: "the method", example_de: "Welche Methode ist am effektivsten?", example_en: "Which method is most effective?" },
  { id: "198", german: "mitwirken", english: "to participate / to contribute", example_de: "Alle Bürger können mitwirken.", example_en: "All citizens can participate." },
  { id: "199", german: "nachvollziehen", english: "to understand / to follow", example_de: "Ich kann deine Entscheidung nicht nachvollziehen.", example_en: "I cannot understand your decision." },
  { id: "200", german: "die Neigung", english: "the inclination / tendency", example_de: "Er hat eine Neigung zur Perfektionismus.", example_en: "He has an inclination towards perfectionism." },
  { id: "201", german: "neutral", english: "neutral", example_de: "In diesem Streit bleibe ich neutral.", example_en: "I remain neutral in this dispute." },
  { id: "202", german: "die Norm", english: "the norm / standard", example_de: "Das entspricht nicht der gesellschaftlichen Norm.", example_en: "That does not correspond to the social norm." },
  { id: "203", german: "offenbar", english: "apparently / evidently", example_de: "Er hat offenbar vergessen, anzurufen.", example_en: "He has apparently forgotten to call." },
  { id: "204", german: "die Pflege", english: "the care / maintenance", example_de: "Die Pflege älterer Menschen ist wichtig.", example_en: "The care of elderly people is important." },
  { id: "205", german: "plausibel", english: "plausible", example_de: "Das klingt plausibel.", example_en: "That sounds plausible." },
  { id: "206", german: "präzise", english: "precise", example_de: "Sei bitte präziser in deiner Aussage.", example_en: "Please be more precise in your statement." },
  { id: "207", german: "die Priorität", english: "the priority", example_de: "Was hat für dich oberste Priorität?", example_en: "What is your top priority?" },
  { id: "208", german: "das Prinzip", english: "the principle", example_de: "Das widerspricht meinen Prinzipien.", example_en: "That contradicts my principles." },
  { id: "209", german: "die Rahmenbedingung", english: "the framework condition", example_de: "Die Rahmenbedingungen müssen stimmen.", example_en: "The framework conditions must be right." },
  { id: "210", german: "realistisch", english: "realistic", example_de: "Sei realistisch in deinen Erwartungen.", example_en: "Be realistic in your expectations." },
  { id: "211", german: "rechtfertigen", english: "to justify", example_de: "Wie kannst du das rechtfertigen?", example_en: "How can you justify that?" },
  { id: "212", german: "die Ressource", english: "the resource", example_de: "Wir müssen Ressourcen besser nutzen.", example_en: "We must use resources better." },
  { id: "213", german: "die Rücksicht", english: "the consideration / regard", example_de: "Nimm Rücksicht auf andere.", example_en: "Show consideration for others." },
  { id: "214", german: "sachlich", english: "factual / objective", example_de: "Bleib bitte sachlich.", example_en: "Please stay objective." },
  { id: "215", german: "die Schlüsselrolle", english: "the key role", example_de: "Bildung spielt eine Schlüsselrolle.", example_en: "Education plays a key role." },
  { id: "216", german: "scheitern", english: "to fail", example_de: "Das Projekt ist gescheitert.", example_en: "The project has failed." },
  { id: "217", german: "die Skepsis", english: "the skepticism", example_de: "Es gibt Skepsis gegenüber neuen Technologien.", example_en: "There is skepticism towards new technologies." },
  { id: "218", german: "skeptisch", english: "skeptical", example_de: "Ich bin skeptisch gegenüber dieser Idee.", example_en: "I am skeptical about this idea." },
  { id: "219", german: "die Spannung", english: "the tension / excitement", example_de: "Die Spannung zwischen beiden Parteien wächst.", example_en: "The tension between the two parties is growing." },
  { id: "220", german: "spezifisch", english: "specific", example_de: "Kannst du spezifischer sein?", example_en: "Can you be more specific?" },
  { id: "221", german: "der Standpunkt", english: "the point of view", example_de: "Ich vertrete einen klaren Standpunkt.", example_en: "I hold a clear point of view." },
  { id: "222", german: "stattfinden", english: "to take place", example_de: "Die Konferenz findet nächste Woche statt.", example_en: "The conference takes place next week." },
  { id: "223", german: "der Stellenwert", english: "the value / importance", example_de: "Familie hat für mich einen hohen Stellenwert.", example_en: "Family has a high value for me." },
  { id: "224", german: "streben nach", english: "to strive for / to aspire to", example_de: "Er strebt nach Perfektion.", example_en: "He strives for perfection." },
  { id: "225", german: "subventionieren", english: "to subsidize", example_de: "Der Staat subventioniert erneuerbare Energien.", example_en: "The state subsidizes renewable energies." },
  { id: "226", german: "die Tendenz", english: "the tendency / trend", example_de: "Die Tendenz geht in die richtige Richtung.", example_en: "The tendency is going in the right direction." },
  { id: "227", german: "die These", english: "the thesis / argument", example_de: "Kannst du deine These belegen?", example_en: "Can you support your thesis?" },
  { id: "228", german: "transparent", english: "transparent", example_de: "Die Entscheidungen sollten transparent sein.", example_en: "The decisions should be transparent." },
  { id: "229", german: "die Transparenz", english: "the transparency", example_de: "Transparenz schafft Vertrauen.", example_en: "Transparency creates trust." },
  { id: "230", german: "überdenken", english: "to reconsider / to rethink", example_de: "Du solltest deine Entscheidung überdenken.", example_en: "You should reconsider your decision." },
  { id: "231", german: "übereinstimmen", english: "to agree / to match", example_de: "Unsere Meinungen stimmen überein.", example_en: "Our opinions agree." },
  { id: "232", german: "die Übereinstimmung", english: "the agreement / correspondence", example_de: "Es gibt keine Übereinstimmung zwischen den Daten.", example_en: "There is no agreement between the data." },
  { id: "233", german: "das Unbehagen", english: "the unease / discomfort", example_de: "Das Thema löst Unbehagen aus.", example_en: "The topic causes unease." },
  { id: "234", german: "unterstreichen", english: "to underline / to emphasize", example_de: "Das unterstreicht die Bedeutung des Themas.", example_en: "That underlines the importance of the topic." },
  { id: "235", german: "die Umsetzung", english: "the implementation", example_de: "Die Umsetzung des Plans ist schwierig.", example_en: "The implementation of the plan is difficult." },
  { id: "236", german: "unzureichend", english: "insufficient / inadequate", example_de: "Die Maßnahmen sind unzureichend.", example_en: "The measures are insufficient." },
  { id: "237", german: "verallgemeinern", english: "to generalize", example_de: "Man sollte nicht verallgemeinern.", example_en: "One should not generalize." },
  { id: "238", german: "verantwortungsvoll", english: "responsible", example_de: "Handle verantwortungsvoll.", example_en: "Act responsibly." },
  { id: "239", german: "verbindlich", english: "binding / obligatory / reliable", example_de: "Diese Regelung ist verbindlich.", example_en: "This regulation is binding." },
  { id: "240", german: "verbreiten", english: "to spread / to disseminate", example_de: "Falsche Informationen verbreiten sich schnell.", example_en: "False information spreads quickly." },
  { id: "241", german: "verfügen über", english: "to have / to possess", example_de: "Er verfügt über viel Erfahrung.", example_en: "He has a lot of experience." },
  { id: "242", german: "verhandeln", english: "to negotiate", example_de: "Beide Parteien verhandeln über einen Kompromiss.", example_en: "Both parties negotiate a compromise." },
  { id: "243", german: "die Verhandlung", english: "the negotiation", example_de: "Die Verhandlungen verlaufen gut.", example_en: "The negotiations are going well." },
  { id: "244", german: "verlangen", english: "to demand / to require", example_de: "Die Situation verlangt sofortiges Handeln.", example_en: "The situation demands immediate action." },
  { id: "245", german: "verringern", english: "to reduce", example_de: "Wir müssen den Ausstoß verringern.", example_en: "We must reduce the output." },
  { id: "246", german: "verschlechtern", english: "to worsen / to deteriorate", example_de: "Die Lage hat sich verschlechtert.", example_en: "The situation has deteriorated." },
  { id: "247", german: "die Verschlechterung", english: "the deterioration / worsening", example_de: "Die Verschlechterung der Lage ist besorgniserregend.", example_en: "The deterioration of the situation is worrying." },
  { id: "248", german: "verstehen unter", english: "to understand by", example_de: "Was verstehst du unter Freiheit?", example_en: "What do you understand by freedom?" },
  { id: "249", german: "verwalten", english: "to manage / to administer", example_de: "Er verwaltet das Budget des Unternehmens.", example_en: "He manages the company's budget." },
  { id: "250", german: "die Verwaltung", english: "the administration / management", example_de: "Die Verwaltung ist sehr bürokratisch.", example_en: "The administration is very bureaucratic." },
  { id: "251", german: "die Verpflichtung", english: "the obligation / commitment", example_de: "Wir haben eine Verpflichtung gegenüber der Gesellschaft.", example_en: "We have an obligation towards society." },
  { id: "252", german: "vorzugsweise", english: "preferably", example_de: "Wähle vorzugsweise einen erfahrenen Anbieter.", example_en: "Preferably choose an experienced provider." },
  { id: "253", german: "das Wesen", english: "the essence / nature / being", example_de: "Was ist das Wesen der Demokratie?", example_en: "What is the essence of democracy?" },
  { id: "254", german: "wesentlich", english: "essential / significant", example_de: "Das ist ein wesentlicher Unterschied.", example_en: "That is a significant difference." },
  { id: "255", german: "widmen", english: "to dedicate", example_de: "Sie widmet sich ganz ihrer Arbeit.", example_en: "She dedicates herself entirely to her work." },
  { id: "256", german: "die Wirkung", english: "the effect / impact", example_de: "Die Wirkung des Medikaments ist stark.", example_en: "The effect of the medication is strong." },
  { id: "257", german: "wirkungsvoll", english: "effective / impactful", example_de: "Diese Methode ist sehr wirkungsvoll.", example_en: "This method is very effective." },
  { id: "258", german: "zugunsten", english: "in favor of", example_de: "Die Entscheidung fiel zugunsten der Mehrheit.", example_en: "The decision was made in favor of the majority." },
  { id: "259", german: "zunehmen", english: "to increase / to grow", example_de: "Die Anzahl der Anträge nimmt zu.", example_en: "The number of applications is increasing." },
  { id: "260", german: "zurückführen auf", english: "to attribute to / to trace back to", example_de: "Das lässt sich auf mehrere Ursachen zurückführen.", example_en: "That can be attributed to several causes." },
  { id: "261", german: "die Zunahme", english: "the increase", example_de: "Es gibt eine deutliche Zunahme der Fälle.", example_en: "There is a clear increase in cases." },
  { id: "262", german: "die Zuverlässigkeit", english: "the reliability", example_de: "Zuverlässigkeit ist im Berufsleben wichtig.", example_en: "Reliability is important in professional life." },
  { id: "263", german: "zuverlässig", english: "reliable / dependable", example_de: "Er ist ein zuverlässiger Mitarbeiter.", example_en: "He is a reliable employee." },
  { id: "264", german: "die Zuständigkeit", english: "the responsibility / jurisdiction", example_de: "Das liegt in meiner Zuständigkeit.", example_en: "That is within my responsibility." },
  { id: "265", german: "zuständig", english: "responsible / in charge", example_de: "Wer ist dafür zuständig?", example_en: "Who is responsible for that?" },
  { id: "266", german: "abschätzen", english: "to estimate / to assess", example_de: "Es ist schwer, die Kosten abzuschätzen.", example_en: "It is difficult to estimate the costs." },
  { id: "267", german: "die Akzeptanz", english: "the acceptance", example_de: "Die Akzeptanz in der Bevölkerung ist gering.", example_en: "Acceptance in the population is low." },
  { id: "268", german: "akzeptieren", english: "to accept", example_de: "Ich akzeptiere deine Entscheidung.", example_en: "I accept your decision." },
  { id: "269", german: "die Ambivalenz", english: "the ambivalence", example_de: "In dieser Frage herrscht Ambivalenz.", example_en: "In this question there is ambivalence." },
  { id: "270", german: "ambivalent", english: "ambivalent", example_de: "Ich bin ambivalent gegenüber diesem Thema.", example_en: "I am ambivalent about this topic." },
  { id: "271", german: "anhalten", english: "to persist / to continue", example_de: "Das Problem hält an.", example_en: "The problem persists." },
  { id: "272", german: "anknüpfen", english: "to connect / to link", example_de: "Das knüpft an unsere frühere Diskussion an.", example_en: "That connects to our earlier discussion." },
  { id: "273", german: "anmerken", english: "to note / to remark", example_de: "Ich möchte anmerken, dass das falsch ist.", example_en: "I would like to remark that that is wrong." },
  { id: "274", german: "die Ausnahme", english: "the exception", example_de: "Jede Regel hat ihre Ausnahme.", example_en: "Every rule has its exception." },
  { id: "275", german: "ausschlaggebend", english: "decisive / determining", example_de: "Das war der ausschlaggebende Faktor.", example_en: "That was the decisive factor." },
  { id: "276", german: "der Ausgangspunkt", english: "the starting point", example_de: "Was war der Ausgangspunkt dieser Entwicklung?", example_en: "What was the starting point of this development?" },
  { id: "277", german: "ausweichen", english: "to evade / to avoid", example_de: "Er weicht der Frage aus.", example_en: "He evades the question." },
  { id: "278", german: "die Autonomie", english: "the autonomy", example_de: "Jeder Mensch hat das Recht auf Autonomie.", example_en: "Every person has the right to autonomy." },
  { id: "279", german: "autonom", english: "autonomous", example_de: "Das System arbeitet autonom.", example_en: "The system works autonomously." },
  { id: "280", german: "basieren auf", english: "to be based on", example_de: "Die Theorie basiert auf Fakten.", example_en: "The theory is based on facts." },
  { id: "281", german: "die Belastung", english: "the burden / stress / load", example_de: "Die psychische Belastung ist sehr hoch.", example_en: "The psychological burden is very high." },
  { id: "282", german: "belasten", english: "to burden / to strain", example_de: "Das belastet die Umwelt stark.", example_en: "That heavily burdens the environment." },
  { id: "283", german: "berechtigt", english: "justified / entitled", example_de: "Deine Kritik ist berechtigt.", example_en: "Your criticism is justified." },
  { id: "284", german: "bereitstellen", english: "to provide / to make available", example_de: "Die Regierung stellt Mittel bereit.", example_en: "The government provides funds." },
  { id: "285", german: "der Bürger", english: "the citizen", example_de: "Jeder Bürger hat Rechte und Pflichten.", example_en: "Every citizen has rights and duties." },
  { id: "286", german: "die Bürokratie", english: "the bureaucracy", example_de: "Die Bürokratie verlangsamt den Prozess.", example_en: "Bureaucracy slows down the process." },
  { id: "287", german: "bürokratisch", english: "bureaucratic", example_de: "Das Verfahren ist sehr bürokratisch.", example_en: "The procedure is very bureaucratic." },
  { id: "288", german: "einbeziehen", english: "to involve / to include", example_de: "Wir sollten alle Beteiligten einbeziehen.", example_en: "We should involve all parties concerned." },
  { id: "289", german: "eindeutig", english: "clear / unambiguous", example_de: "Die Antwort ist eindeutig.", example_en: "The answer is clear." },
  { id: "290", german: "die Einheit", english: "the unity / unit", example_de: "Einheit ist in schwierigen Zeiten wichtig.", example_en: "Unity is important in difficult times." },
  { id: "291", german: "einordnen", english: "to classify / to categorize", example_de: "Wie ordnest du das ein?", example_en: "How do you classify that?" },
  { id: "292", german: "die Empfehlung", english: "the recommendation", example_de: "Ich folge deiner Empfehlung.", example_en: "I follow your recommendation." },
  { id: "293", german: "entgegenwirken", english: "to counteract", example_de: "Wir müssen dem Trend entgegenwirken.", example_en: "We must counteract the trend." },
  { id: "294", german: "entnehmen", english: "to take from / to gather from", example_de: "Dem Text entnehme ich, dass er falsch liegt.", example_en: "From the text I gather that he is wrong." },
  { id: "295", german: "die Erkenntnis", english: "the realization / insight / finding", example_de: "Das ist eine wichtige Erkenntnis.", example_en: "That is an important insight." },
  { id: "296", german: "erstrebenswert", english: "desirable / worth striving for", example_de: "Das ist ein erstrebenswertes Ziel.", example_en: "That is a desirable goal." },
  { id: "297", german: "erwägen", english: "to consider / to contemplate", example_de: "Ich erwäge, den Job zu wechseln.", example_en: "I am considering changing jobs." },
  { id: "298", german: "etwaig", english: "possible / any", example_de: "Etwaige Probleme sollten sofort gemeldet werden.", example_en: "Any possible problems should be reported immediately." },
  { id: "299", german: "faktisch", english: "factual / in effect", example_de: "Das ist faktisch korrekt.", example_en: "That is factually correct." },
  { id: "300", german: "die Flexibilität", english: "the flexibility", example_de: "Flexibilität ist in der modernen Arbeitswelt wichtig.", example_en: "Flexibility is important in the modern working world." },
  { id: "301", german: "flexibel", english: "flexible", example_de: "Ich bin zeitlich sehr flexibel.", example_en: "I am very flexible with my time." },
  { id: "302", german: "die Folgerung", english: "the conclusion / deduction", example_de: "Welche Folgerung ziehst du daraus?", example_en: "What conclusion do you draw from that?" },
  { id: "303", german: "die Fürsorge", english: "the care / welfare", example_de: "Fürsorge für andere ist ein Zeichen von Stärke.", example_en: "Care for others is a sign of strength." },
  { id: "304", german: "gegenüberstehen", english: "to face / to be confronted with", example_de: "Wir stehen einer großen Herausforderung gegenüber.", example_en: "We are facing a great challenge." },
  { id: "305", german: "gelingen", english: "to succeed", example_de: "Es ist mir gelungen, das Problem zu lösen.", example_en: "I succeeded in solving the problem." },
  { id: "306", german: "geltend machen", english: "to assert / to claim", example_de: "Er macht seine Rechte geltend.", example_en: "He asserts his rights." },
  { id: "307", german: "die Gemeinschaft", english: "the community", example_de: "Wir müssen als Gemeinschaft handeln.", example_en: "We must act as a community." },
  { id: "308", german: "die Gerechtigkeit", english: "the justice / fairness", example_de: "Soziale Gerechtigkeit ist ein wichtiges Thema.", example_en: "Social justice is an important topic." },
  { id: "309", german: "gerecht", english: "fair / just", example_de: "Das System ist nicht immer gerecht.", example_en: "The system is not always fair." },
  { id: "310", german: "das Gewissen", english: "the conscience", example_de: "Mein Gewissen lässt mir keine Ruhe.", example_en: "My conscience gives me no rest." },
  { id: "311", german: "glaubwürdig", english: "credible / trustworthy", example_de: "Die Quelle ist nicht glaubwürdig.", example_en: "The source is not credible." },
  { id: "312", german: "die Glaubwürdigkeit", english: "the credibility", example_de: "Die Glaubwürdigkeit der Presse steht auf dem Spiel.", example_en: "The credibility of the press is at stake." },
  { id: "313", german: "das Gleichgewicht", english: "the balance", example_de: "Wir brauchen ein besseres Gleichgewicht.", example_en: "We need a better balance." },
  { id: "314", german: "der Handlungsbedarf", english: "the need for action", example_de: "Es besteht dringender Handlungsbedarf.", example_en: "There is an urgent need for action." },
  { id: "315", german: "heranziehen", english: "to draw on / to use as reference", example_de: "Wir können diese Studie heranziehen.", example_en: "We can draw on this study." },
  { id: "316", german: "herausfinden", english: "to find out", example_de: "Ich versuche herauszufinden, was passiert ist.", example_en: "I am trying to find out what happened." },
  { id: "317", german: "heterogen", english: "heterogeneous / diverse", example_de: "Die Gruppe ist sehr heterogen.", example_en: "The group is very heterogeneous." },
  { id: "318", german: "die Hierarchie", english: "the hierarchy", example_de: "In diesem Unternehmen gibt es eine flache Hierarchie.", example_en: "This company has a flat hierarchy." },
  { id: "319", german: "homogen", english: "homogeneous", example_de: "Die Gruppe ist sehr homogen.", example_en: "The group is very homogeneous." },
  { id: "320", german: "das Ideal", english: "the ideal", example_de: "Das entspricht dem Ideal nicht.", example_en: "That does not correspond to the ideal." },
  { id: "321", german: "idealistisch", english: "idealistic", example_de: "Sein Ansatz ist zu idealistisch.", example_en: "His approach is too idealistic." },
  { id: "322", german: "in Frage stellen", english: "to question / to call into question", example_de: "Das stellt unsere gesamte Strategie in Frage.", example_en: "That calls our entire strategy into question." },
  { id: "323", german: "infolge", english: "as a result of / due to", example_de: "Infolge des Sturms gab es Stromausfälle.", example_en: "As a result of the storm there were power outages." },
  { id: "324", german: "das Interesse", english: "the interest", example_de: "Das liegt im öffentlichen Interesse.", example_en: "That is in the public interest." },
  { id: "325", german: "das Kernproblem", english: "the core problem", example_de: "Was ist das Kernproblem?", example_en: "What is the core problem?" },
  { id: "326", german: "die Kommunikation", english: "the communication", example_de: "Gute Kommunikation ist der Schlüssel.", example_en: "Good communication is the key." },
  { id: "327", german: "kommunizieren", english: "to communicate", example_de: "Wir müssen besser kommunizieren.", example_en: "We need to communicate better." },
  { id: "328", german: "die Kooperation", english: "the cooperation", example_de: "Internationale Kooperation ist notwendig.", example_en: "International cooperation is necessary." },
  { id: "329", german: "kooperieren", english: "to cooperate", example_de: "Beide Länder kooperieren eng.", example_en: "Both countries cooperate closely." },
  { id: "330", german: "langfristig", english: "long-term", example_de: "Wir denken langfristig.", example_en: "We think long-term." },
  { id: "331", german: "die Lücke", english: "the gap", example_de: "Es gibt eine Lücke zwischen Theorie und Praxis.", example_en: "There is a gap between theory and practice." },
  { id: "332", german: "die Mehrheit", english: "the majority", example_de: "Die Mehrheit der Bevölkerung ist dafür.", example_en: "The majority of the population is in favor." },
  { id: "333", german: "die Minderheit", english: "the minority", example_de: "Die Rechte von Minderheiten müssen geschützt werden.", example_en: "The rights of minorities must be protected." },
  { id: "334", german: "der Missbrauch", english: "the abuse / misuse", example_de: "Missbrauch von Macht ist inakzeptabel.", example_en: "Abuse of power is unacceptable." },
  { id: "335", german: "nachdrücklich", english: "emphatically / strongly", example_de: "Ich empfehle das nachdrücklich.", example_en: "I strongly recommend that." },
  { id: "336", german: "nachhaltig wirken", english: "to have a lasting effect", example_de: "Diese Erfahrung hat nachhaltig auf mich gewirkt.", example_en: "This experience had a lasting effect on me." },
  { id: "337", german: "nahelegen", english: "to suggest / to imply", example_de: "Die Daten legen nahe, dass wir falsch lagen.", example_en: "The data suggest that we were wrong." },
  { id: "338", german: "die Nüchternheit", english: "the soberness / objectivity", example_de: "Mit mehr Nüchternheit lässt sich besser urteilen.", example_en: "With more objectivity one can judge better." },
  { id: "339", german: "pragmatisch", english: "pragmatic", example_de: "Wir brauchen einen pragmatischen Ansatz.", example_en: "We need a pragmatic approach." },
  { id: "340", german: "der Pragmatismus", english: "the pragmatism", example_de: "Pragmatismus ist in der Politik wichtig.", example_en: "Pragmatism is important in politics." },
  { id: "341", german: "die Praxis", english: "the practice / reality", example_de: "Theorie und Praxis sind oft verschieden.", example_en: "Theory and practice are often different." },
  { id: "342", german: "präventiv", english: "preventive", example_de: "Präventive Maßnahmen sind besser als Reaktionen.", example_en: "Preventive measures are better than reactions." },
  { id: "343", german: "der Rahmen", english: "the framework / frame", example_de: "Im Rahmen dieses Projekts ist das möglich.", example_en: "Within the framework of this project that is possible." },
  { id: "344", german: "rationalisieren", english: "to rationalize", example_de: "Das Unternehmen muss Prozesse rationalisieren.", example_en: "The company must rationalize processes." },
  { id: "345", german: "reagieren auf", english: "to react to / to respond to", example_de: "Wie reagierst du auf Kritik?", example_en: "How do you react to criticism?" },
  { id: "346", german: "realisierbar", english: "feasible / achievable", example_de: "Ist das realisierbar?", example_en: "Is that feasible?" },
  { id: "347", german: "die Reform", english: "the reform", example_de: "Das System braucht grundlegende Reformen.", example_en: "The system needs fundamental reforms." },
  { id: "348", german: "die Regelung", english: "the regulation", example_de: "Es bedarf einer klaren Regelung.", example_en: "A clear regulation is needed." },
  { id: "349", german: "relativieren", english: "to put into perspective", example_de: "Man sollte das ein bisschen relativieren.", example_en: "One should put that into perspective a little." },
  { id: "350", german: "das Resultat", english: "the result", example_de: "Das Resultat war enttäuschend.", example_en: "The result was disappointing." },
  { id: "351", german: "die Schwäche", english: "the weakness", example_de: "Jeder hat Stärken und Schwächen.", example_en: "Everyone has strengths and weaknesses." },
  { id: "352", german: "die Stärke", english: "the strength", example_de: "Kommunikation ist seine größte Stärke.", example_en: "Communication is his greatest strength." },
  { id: "353", german: "die Solidarität", english: "the solidarity", example_de: "Solidarität ist in Krisenzeiten wichtig.", example_en: "Solidarity is important in times of crisis." },
  { id: "354", german: "solidarisch", english: "solidary / in solidarity", example_de: "Wir handeln solidarisch.", example_en: "We act in solidarity." },
  { id: "355", german: "die Souveränität", english: "the sovereignty", example_de: "Die Souveränität des Landes muss respektiert werden.", example_en: "The sovereignty of the country must be respected." },
  { id: "356", german: "die Stabilität", english: "the stability", example_de: "Politische Stabilität ist wichtig für Investitionen.", example_en: "Political stability is important for investments." },
  { id: "357", german: "stabil", english: "stable", example_de: "Die Lage ist stabil.", example_en: "The situation is stable." },
  { id: "358", german: "stigmatisieren", english: "to stigmatize", example_de: "Man sollte Menschen nicht stigmatisieren.", example_en: "One should not stigmatize people." },
  { id: "359", german: "die Struktur", english: "the structure", example_de: "Die Struktur des Unternehmens ist klar.", example_en: "The structure of the company is clear." },
  { id: "360", german: "strukturieren", english: "to structure", example_de: "Du solltest deine Gedanken besser strukturieren.", example_en: "You should structure your thoughts better." },
  { id: "361", german: "die Toleranz", english: "the tolerance", example_de: "Toleranz ist in einer vielfältigen Gesellschaft wichtig.", example_en: "Tolerance is important in a diverse society." },
  { id: "362", german: "tolerieren", english: "to tolerate", example_de: "Das kann ich nicht tolerieren.", example_en: "I cannot tolerate that." },
  { id: "363", german: "die Übernahme", english: "the takeover / assumption", example_de: "Die Übernahme der Verantwortung ist wichtig.", example_en: "The assumption of responsibility is important." },
  { id: "364", german: "die Ungleichheit", english: "the inequality", example_de: "Soziale Ungleichheit nimmt zu.", example_en: "Social inequality is increasing." },
  { id: "365", german: "unparteiisch", english: "impartial / unbiased", example_de: "Der Richter muss unparteiisch sein.", example_en: "The judge must be impartial." },
  { id: "366", german: "unrealistisch", english: "unrealistic", example_de: "Deine Erwartungen sind unrealistisch.", example_en: "Your expectations are unrealistic." },
  { id: "367", german: "unterschätzen", english: "to underestimate", example_de: "Man sollte den Gegner nicht unterschätzen.", example_en: "One should not underestimate the opponent." },
  { id: "368", german: "überschätzen", english: "to overestimate", example_de: "Ich habe meine Fähigkeiten überschätzt.", example_en: "I overestimated my abilities." },
  { id: "369", german: "vereinbaren", english: "to agree on / to arrange", example_de: "Lass uns einen Termin vereinbaren.", example_en: "Let us arrange an appointment." },
  { id: "370", german: "die Vereinbarung", english: "the agreement / arrangement", example_de: "Wir haben eine Vereinbarung getroffen.", example_en: "We have reached an agreement." },
  { id: "371", german: "vermitteln", english: "to convey / to mediate", example_de: "Der Lehrer vermittelt Wissen.", example_en: "The teacher conveys knowledge." },
  { id: "372", german: "vernachlässigen", english: "to neglect", example_de: "Du vernachlässigst deine Gesundheit.", example_en: "You are neglecting your health." },
  { id: "373", german: "das Vorurteil", english: "the prejudice", example_de: "Vorurteile muss man überwinden.", example_en: "One must overcome prejudices." },
  { id: "374", german: "wechselseitig", english: "mutual / reciprocal", example_de: "Das ist ein wechselseitiger Prozess.", example_en: "That is a mutual process." },
  { id: "375", german: "weitreichend", english: "far-reaching", example_de: "Das hat weitreichende Konsequenzen.", example_en: "That has far-reaching consequences." },
  { id: "376", german: "widerlegen", english: "to refute / to disprove", example_de: "Diese Theorie wurde widerlegt.", example_en: "This theory was disproved." },
  { id: "377", german: "die Zielsetzung", english: "the objective / goal-setting", example_de: "Klare Zielsetzung ist entscheidend.", example_en: "Clear objective-setting is crucial." },
  { id: "378", german: "die Zugehörigkeit", english: "the belonging / membership", example_de: "Das Gefühl der Zugehörigkeit ist wichtig.", example_en: "The feeling of belonging is important." },
  { id: "379", german: "zuordnen", english: "to assign / to categorize", example_de: "Kannst du das einer Kategorie zuordnen?", example_en: "Can you assign that to a category?" },
  { id: "380", german: "der Zusammenschluss", english: "the merger / union", example_de: "Der Zusammenschluss beider Firmen war erfolgreich.", example_en: "The merger of both companies was successful." },
  { id: "381", german: "abweichen", english: "to deviate / to differ", example_de: "Das weicht von unserer Planung ab.", example_en: "That deviates from our planning." },
  { id: "382", german: "die Agilität", english: "the agility", example_de: "Agilität ist in der modernen Arbeitswelt gefragt.", example_en: "Agility is in demand in the modern working world." },
  { id: "383", german: "angemessen", english: "appropriate / suitable", example_de: "Das war keine angemessene Reaktion.", example_en: "That was not an appropriate reaction." },
  { id: "384", german: "anhalten", english: "to last / to continue", example_de: "Die Verhandlungen halten an.", example_en: "The negotiations continue." },
  { id: "385", german: "anstreben", english: "to aim for / to aspire to", example_de: "Wir streben eine bessere Lösung an.", example_en: "We aim for a better solution." },
  { id: "386", german: "das Argument", english: "the argument", example_de: "Dein Argument ist überzeugend.", example_en: "Your argument is convincing." },
  { id: "387", german: "argumentieren", english: "to argue", example_de: "Er argumentiert sehr sachlich.", example_en: "He argues very objectively." },
  { id: "388", german: "aufzeigen", english: "to show / to point out", example_de: "Der Bericht zeigt Probleme auf.", example_en: "The report points out problems." },
  { id: "389", german: "die Ausgewogenheit", english: "the balance / impartiality", example_de: "Die Ausgewogenheit des Berichts ist fragwürdig.", example_en: "The balance of the report is questionable." },
  { id: "390", german: "ausgewogen", english: "balanced", example_de: "Der Artikel ist ausgewogen.", example_en: "The article is balanced." },
  { id: "391", german: "beachten", english: "to observe / to pay attention to", example_de: "Bitte beachte die Regeln.", example_en: "Please observe the rules." },
  { id: "392", german: "bedingen", english: "to cause / to be conditional on", example_de: "Erfolg bedingt harte Arbeit.", example_en: "Success is conditional on hard work." },
  { id: "393", german: "befürworten", english: "to support / to advocate", example_de: "Ich befürworte diesen Vorschlag.", example_en: "I support this proposal." },
  { id: "394", german: "begreifen", english: "to grasp / to understand", example_de: "Er begreift die Situation nicht.", example_en: "He does not grasp the situation." },
  { id: "395", german: "das Bemühen", english: "the effort / endeavor", example_de: "Trotz aller Bemühungen scheiterte das Projekt.", example_en: "Despite all efforts the project failed." },
  { id: "396", german: "benennen", english: "to name / to identify", example_de: "Kannst du das Problem benennen?", example_en: "Can you name the problem?" },
  { id: "397", german: "die Beobachtung", english: "the observation", example_de: "Das ist eine interessante Beobachtung.", example_en: "That is an interesting observation." },
  { id: "398", german: "beobachten", english: "to observe", example_de: "Wir beobachten die Situation genau.", example_en: "We observe the situation closely." },
  { id: "399", german: "bescheinigen", english: "to certify / to confirm", example_de: "Das Dokument bescheinigt seine Qualifikation.", example_en: "The document certifies his qualification." },
  { id: "400", german: "die Bescheinigung", english: "the certificate / confirmation", example_de: "Ich brauche eine Bescheinigung.", example_en: "I need a certificate." },
  { id: "401", german: "das Bewusstsein", english: "the awareness / consciousness", example_de: "Das Bewusstsein für Umweltfragen wächst.", example_en: "Awareness of environmental issues is growing." },
  { id: "402", german: "differenziert", english: "nuanced / differentiated", example_de: "Du solltest differenzierter denken.", example_en: "You should think in a more nuanced way." },
  { id: "403", german: "die Dynamik", english: "the dynamics", example_de: "Die Dynamik in der Gruppe ist schwierig.", example_en: "The dynamics in the group are difficult." },
  { id: "404", german: "dynamisch", english: "dynamic", example_de: "Der Markt ist sehr dynamisch.", example_en: "The market is very dynamic." },
  { id: "405", german: "die Effizienz", english: "the efficiency", example_de: "Wir müssen die Effizienz steigern.", example_en: "We need to increase efficiency." },
  { id: "406", german: "effizient", english: "efficient", example_de: "Das ist eine effiziente Methode.", example_en: "That is an efficient method." },
  { id: "407", german: "ehrenamtlich", english: "voluntary / on a voluntary basis", example_de: "Er arbeitet ehrenamtlich für eine NGO.", example_en: "He works voluntarily for an NGO." },
  { id: "408", german: "die Eigenverantwortung", english: "the personal responsibility", example_de: "Jeder trägt Eigenverantwortung.", example_en: "Everyone bears personal responsibility." },
  { id: "409", german: "einräumen", english: "to admit / to concede", example_de: "Ich muss einräumen, dass ich falsch lag.", example_en: "I must admit that I was wrong." },
  { id: "410", german: "die Einsicht", english: "the insight / realization", example_de: "Er zeigt keine Einsicht.", example_en: "He shows no insight." },
  { id: "411", german: "die Empathie", english: "the empathy", example_de: "Empathie ist eine wichtige soziale Fähigkeit.", example_en: "Empathy is an important social skill." },
  { id: "412", german: "empathisch", english: "empathetic", example_de: "Sie ist sehr empathisch.", example_en: "She is very empathetic." },
  { id: "413", german: "entgegen", english: "contrary to / against", example_de: "Entgegen meiner Erwartung war es einfach.", example_en: "Contrary to my expectation it was easy." },
  { id: "414", german: "die Ethik", english: "the ethics", example_de: "Ethik spielt in der Medizin eine große Rolle.", example_en: "Ethics plays a big role in medicine." },
  { id: "415", german: "ethisch", english: "ethical", example_de: "Das ist ethisch bedenklich.", example_en: "That is ethically questionable." },
  { id: "416", german: "evidenzbasiert", english: "evidence-based", example_de: "Die Entscheidung sollte evidenzbasiert sein.", example_en: "The decision should be evidence-based." },
  { id: "417", german: "der Fachmann", english: "the expert / specialist", example_de: "Er ist ein anerkannter Fachmann.", example_en: "He is a recognized expert." },
  { id: "418", german: "die Fachkenntnis", english: "the expertise / specialist knowledge", example_de: "Für diese Stelle sind Fachkenntnisse nötig.", example_en: "Specialist knowledge is required for this position." },
  { id: "419", german: "festlegen", english: "to determine / to set", example_de: "Wir müssen die Ziele festlegen.", example_en: "We need to set the goals." },
  { id: "420", german: "die Forderung", english: "the demand", example_de: "Die Forderungen wurden erfüllt.", example_en: "The demands were met." },
  { id: "421", german: "gegebenenfalls", english: "if necessary / where applicable", example_de: "Gegebenenfalls können wir den Termin verschieben.", example_en: "If necessary we can postpone the appointment." },
  { id: "422", german: "der Gegensatz", english: "the contrast / opposite", example_de: "Im Gegensatz dazu steht folgendes Argument.", example_en: "In contrast to that stands the following argument." },
  { id: "423", german: "das Gegenüber", english: "the counterpart / opposite side", example_de: "Zeige deinem Gegenüber Respekt.", example_en: "Show respect to your counterpart." },
  { id: "424", german: "die Gleichgültigkeit", english: "the indifference", example_de: "Gleichgültigkeit ist gefährlich.", example_en: "Indifference is dangerous." },
  { id: "425", german: "gleichgültig", english: "indifferent", example_de: "Er ist dem Thema gegenüber gleichgültig.", example_en: "He is indifferent to the topic." },
  { id: "426", german: "die Grenze", english: "the border / limit", example_de: "Es gibt Grenzen, die man nicht überschreiten sollte.", example_en: "There are limits that one should not cross." },
  { id: "427", german: "die Herausforderung", english: "the challenge", example_de: "Das ist eine echte Herausforderung.", example_en: "That is a real challenge." },
  { id: "428", german: "das Ideal", english: "the ideal", example_de: "Das ist weit vom Ideal entfernt.", example_en: "That is far from the ideal." },
  { id: "429", german: "indem", english: "by (doing something)", example_de: "Man lernt, indem man Fehler macht.", example_en: "One learns by making mistakes." },
  { id: "430", german: "infrage kommen", english: "to be considered / to be an option", example_de: "Das kommt für mich nicht infrage.", example_en: "That is not an option for me." },
  { id: "431", german: "die Infrastruktur", english: "the infrastructure", example_de: "Die Infrastruktur muss verbessert werden.", example_en: "The infrastructure needs to be improved." },
  { id: "432", german: "der Inhalt", english: "the content", example_de: "Der Inhalt des Berichts ist interessant.", example_en: "The content of the report is interesting." },
  { id: "433", german: "inhaltlich", english: "in terms of content", example_de: "Inhaltlich stimme ich dir zu.", example_en: "In terms of content I agree with you." },
  { id: "434", german: "die Instanz", english: "the authority / instance", example_de: "Das muss durch die zuständige Instanz geregelt werden.", example_en: "That must be regulated by the responsible authority." },
  { id: "435", german: "interkulturell", english: "intercultural", example_de: "Interkulturelle Kompetenz ist sehr gefragt.", example_en: "Intercultural competence is in great demand." },
  { id: "436", german: "die Intuition", english: "the intuition", example_de: "Vertraue deiner Intuition.", example_en: "Trust your intuition." },
  { id: "437", german: "intuitiv", english: "intuitive", example_de: "Die Bedienung ist intuitiv.", example_en: "The operation is intuitive." },
  { id: "438", german: "die Irrationalität", english: "the irrationality", example_de: "Irrationalität führt zu Fehlern.", example_en: "Irrationality leads to mistakes." },
  { id: "439", german: "irrational", english: "irrational", example_de: "Das ist eine irrationale Entscheidung.", example_en: "That is an irrational decision." },
  { id: "440", german: "die Kapazität", english: "the capacity", example_de: "Die Kapazität ist erschöpft.", example_en: "The capacity is exhausted." },
  { id: "441", german: "kennzeichnen", english: "to characterize / to mark", example_de: "Was kennzeichnet eine gute Führungskraft?", example_en: "What characterizes a good leader?" },
  { id: "442", german: "die Kernaussage", english: "the key message", example_de: "Was ist die Kernaussage des Textes?", example_en: "What is the key message of the text?" },
  { id: "443", german: "die Klarheit", english: "the clarity", example_de: "Klarheit in der Kommunikation ist wichtig.", example_en: "Clarity in communication is important." },
  { id: "444", german: "kollektiv", english: "collective", example_de: "Das ist eine kollektive Entscheidung.", example_en: "That is a collective decision." },
  { id: "445", german: "die Komplexität", english: "the complexity", example_de: "Die Komplexität des Themas ist hoch.", example_en: "The complexity of the topic is high." },
  { id: "446", german: "der Konsens", english: "the consensus", example_de: "Wir haben einen Konsens gefunden.", example_en: "We have found a consensus." },
  { id: "447", german: "konstruktiv", english: "constructive", example_de: "Dein Feedback war sehr konstruktiv.", example_en: "Your feedback was very constructive." },
  { id: "448", german: "kurzfristig", english: "short-term", example_de: "Das ist nur eine kurzfristige Lösung.", example_en: "That is only a short-term solution." },
  { id: "449", german: "die Lehre", english: "the lesson / doctrine", example_de: "Welche Lehre ziehst du daraus?", example_en: "What lesson do you draw from that?" },
  { id: "450", german: "legitimieren", english: "to legitimize", example_de: "Wie lässt sich das legitimieren?", example_en: "How can that be legitimized?" },
  { id: "451", german: "die Legitimität", english: "the legitimacy", example_de: "Die Legitimität der Entscheidung ist fraglich.", example_en: "The legitimacy of the decision is questionable." },
  { id: "452", german: "die Lösungsstrategie", english: "the solution strategy", example_de: "Wir brauchen eine bessere Lösungsstrategie.", example_en: "We need a better solution strategy." },
  { id: "453", german: "mäßigen", english: "to moderate / to restrain", example_de: "Du solltest deine Aussagen mäßigen.", example_en: "You should moderate your statements." },
  { id: "454", german: "mittelfristig", english: "medium-term", example_de: "Mittelfristig planen wir eine Expansion.", example_en: "In the medium term we plan an expansion." },
  { id: "455", german: "die Möglichkeit", english: "the possibility / option", example_de: "Es gibt verschiedene Möglichkeiten.", example_en: "There are various possibilities." },
  { id: "456", german: "die Nachhaltigkeit", english: "the sustainability", example_de: "Nachhaltigkeit muss in alle Bereiche integriert werden.", example_en: "Sustainability must be integrated into all areas." },
  { id: "457", german: "nahezu", english: "almost / nearly", example_de: "Das ist nahezu unmöglich.", example_en: "That is nearly impossible." },
  { id: "458", german: "das Narrativ", english: "the narrative", example_de: "Das dominante Narrativ muss hinterfragt werden.", example_en: "The dominant narrative must be questioned." },
  { id: "459", german: "die Objektivität", english: "the objectivity", example_de: "Objektivität ist in der Wissenschaft wichtig.", example_en: "Objectivity is important in science." },
  { id: "460", german: "die Offenheit", english: "the openness", example_de: "Offenheit fördert gute Zusammenarbeit.", example_en: "Openness promotes good cooperation." },
  { id: "461", german: "offen", english: "open / frank", example_de: "Sei bitte offen und ehrlich.", example_en: "Please be open and honest." },
  { id: "462", german: "die Orientierung", english: "the orientation / guidance", example_de: "Die Orientierung im neuen System fällt schwer.", example_en: "Orientation in the new system is difficult." },
  { id: "463", german: "orientieren", english: "to orient / to align", example_de: "Wir orientieren uns an den Bedürfnissen der Kunden.", example_en: "We align ourselves with the needs of customers." },
  { id: "464", german: "pauschal", english: "blanket / sweeping", example_de: "Das ist eine pauschale Aussage.", example_en: "That is a sweeping statement." },
  { id: "465", german: "die Pauschalisierung", english: "the generalization", example_de: "Pauschalisierungen sind gefährlich.", example_en: "Generalizations are dangerous." },
  { id: "466", german: "die Problemlösung", english: "the problem-solving", example_de: "Kreative Problemlösung ist gefragt.", example_en: "Creative problem-solving is in demand." },
  { id: "467", german: "der Prozess", english: "the process", example_de: "Der Prozess braucht Zeit.", example_en: "The process takes time." },
  { id: "468", german: "die Qualifikation", english: "the qualification", example_de: "Welche Qualifikationen bringt er mit?", example_en: "What qualifications does he have?" },
  { id: "469", german: "die Rationalität", english: "the rationality", example_de: "Rationalität allein reicht nicht aus.", example_en: "Rationality alone is not enough." },
  { id: "470", german: "rational", english: "rational", example_de: "Das ist eine rationale Entscheidung.", example_en: "That is a rational decision." },
  { id: "471", german: "realisieren", english: "to realize / to implement", example_de: "Wir wollen das Projekt realisieren.", example_en: "We want to implement the project." },
  { id: "472", german: "die Rechenschaft", english: "the accountability", example_de: "Er muss Rechenschaft ablegen.", example_en: "He must be held accountable." },
  { id: "473", german: "rückläufig", english: "declining / decreasing", example_de: "Die Zahlen sind rückläufig.", example_en: "The numbers are declining." },
  { id: "474", german: "der Rückschluss", english: "the conclusion / inference", example_de: "Welchen Rückschluss zieht man daraus?", example_en: "What conclusion does one draw from that?" },
  { id: "475", german: "das Scheitern", english: "the failure", example_de: "Scheitern gehört zum Lernen.", example_en: "Failure is part of learning." },
  { id: "476", german: "selbstkritisch", english: "self-critical", example_de: "Man sollte selbstkritisch sein.", example_en: "One should be self-critical." },
  { id: "477", german: "die Selbstreflexion", english: "the self-reflection", example_de: "Selbstreflexion fördert persönliches Wachstum.", example_en: "Self-reflection promotes personal growth." },
  { id: "478", german: "sensibilisieren", english: "to sensitize / to raise awareness", example_de: "Wir müssen die Bevölkerung sensibilisieren.", example_en: "We need to raise awareness among the population." },
  { id: "479", german: "die Sorgfalt", english: "the care / diligence", example_de: "Sorgfalt ist bei dieser Arbeit wichtig.", example_en: "Care is important in this work." },
  { id: "480", german: "sorgfältig", english: "careful / diligent", example_de: "Lies den Vertrag sorgfältig.", example_en: "Read the contract carefully." },
  { id: "481", german: "die Subjektivität", english: "the subjectivity", example_de: "Subjektivität kann die Wahrnehmung verzerren.", example_en: "Subjectivity can distort perception." },
  { id: "482", german: "subjektiv", english: "subjective", example_de: "Das ist eine sehr subjektive Meinung.", example_en: "That is a very subjective opinion." },
  { id: "483", german: "die Tragweite", english: "the scope / implications", example_de: "Die Tragweite der Entscheidung ist enorm.", example_en: "The scope of the decision is enormous." },
  { id: "484", german: "der Trend", english: "the trend", example_de: "Der Trend geht zur Nachhaltigkeit.", example_en: "The trend is towards sustainability." },
  { id: "485", german: "die Überbrückung", english: "the bridging", example_de: "Das ist nur eine Überbrückung.", example_en: "That is only a bridging measure." },
  { id: "486", german: "die Übertragung", english: "the transfer / transmission", example_de: "Die Übertragung von Wissen ist wichtig.", example_en: "The transfer of knowledge is important." },
  { id: "487", german: "umfassend", english: "comprehensive / extensive", example_de: "Wir brauchen eine umfassende Analyse.", example_en: "We need a comprehensive analysis." },
  { id: "488", german: "der Umgang", english: "the handling / dealings", example_de: "Der Umgang mit Konflikten ist schwierig.", example_en: "Dealing with conflicts is difficult." },
  { id: "489", german: "unvermeidlich", english: "inevitable", example_de: "Veränderungen sind unvermeidlich.", example_en: "Changes are inevitable." },
  { id: "490", german: "die Ursachenforschung", english: "the root cause analysis", example_de: "Ursachenforschung ist der erste Schritt.", example_en: "Root cause analysis is the first step." },
  { id: "491", german: "der Verarbeitungsprozess", english: "the processing / working through", example_de: "Der Verarbeitungsprozess dauert Zeit.", example_en: "The processing takes time." },
  { id: "492", german: "verknüpfen", english: "to link / to connect", example_de: "Wie lassen sich diese Ideen verknüpfen?", example_en: "How can these ideas be linked?" },
  { id: "493", german: "verlässlich", english: "reliable / dependable", example_de: "Er ist ein verlässlicher Partner.", example_en: "He is a reliable partner." },
  { id: "494", german: "die Vernetzung", english: "the networking / interconnection", example_de: "Globale Vernetzung hat viele Vorteile.", example_en: "Global networking has many advantages." },
  { id: "495", german: "vielschichtig", english: "multifaceted / complex", example_de: "Das Thema ist vielschichtig.", example_en: "The topic is multifaceted." },
  { id: "496", german: "die Vorgehensweise", english: "the approach / procedure", example_de: "Welche Vorgehensweise empfiehlst du?", example_en: "What approach do you recommend?" },
  { id: "497", german: "das Wertesystem", english: "the value system", example_de: "Jede Kultur hat ihr eigenes Wertesystem.", example_en: "Every culture has its own value system." },
  { id: "498", german: "die Wirklichkeit", english: "the reality", example_de: "Theorie und Wirklichkeit klaffen auseinander.", example_en: "Theory and reality are far apart." },
  { id: "499", german: "die Zivilgesellschaft", english: "civil society", example_de: "Die Zivilgesellschaft spielt eine wichtige Rolle.", example_en: "Civil society plays an important role." },
  { id: "500", german: "die Zukunftsfähigkeit", english: "the future viability / sustainability", example_de: "Zukunftsfähigkeit ist das Ziel jeder Reform.", example_en: "Future viability is the goal of every reform." },
];